### ISSUE TITLE
Review JSDoc comments for accuracy

### ISSUE THREAD

**Issue by JohnathonBowers** [BigSamu/OpenSearch_Changelog_Workflow#35]

**Comment by BigSamu** [comment]
This work will be ideal for checking all functions in the code are correctly defined and described. Possibly the best way to do this work is along unit-testing

**Comment by BigSamu** [comment]
This is already addressed in release [v1.0.0-alpha](https://github.com/BigSamu/OpenSearch_Changelog_Workflow/releases/tag/1.0.0-alpha1)
