### ISSUE TITLE
Revise Documentation - General Update

### ISSUE THREAD

**Issue by JohnathonBowers** [BigSamu/OpenSearch_Changelog_Workflow#38]

**Comment by BigSamu** [comment]
With the recent updates, we need to update the documentation accordingly.

Based on the last meeting with Ashwin, the primary docs for the "CHANGESET AND RELEASE NOTES" project should be located here. This means it is required to have separate docs sections explaining the work for the creation of changesets and the process of release notes, plus details on how to contribute.

Additionally changeset bot should be mentioned in this documentation by referencing it with a link to this [location] (https://github.com/BigSamu/OpenSearch_Changeset_Bot)

**Comment by BigSamu** [comment]
Hi all,

I just created the branch [docs/general-update](https://github.com/BigSamu/OpenSearch_Parse_Changelog_Action/tree/docs/general-update) to work on it for updating documentation in this repo. Please let's use this place for everyone to bring changes. I added all of us as responsible for this issue so we can be aligned and work in the same direction.

**Comment by BigSamu** [comment]
This issue is being closed. Other issues will be address this in a modular way
